apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmaps.yaml
  - crds.yaml
  - deployments.yaml
  - hpas.yaml
  - pdbs.yaml
  - rbac.yaml
  - services.yaml
  - webhooks.yaml
  - patches/certificates.yaml
  - patches/namespaces.yaml
  - patches/policy-mtls.yaml

patches:
  - target:
      kind: ServiceAccount
    path: patches/irsa.yaml
  - target:
      kind: Service
      name: istio-ingressgateway
    path: patches/ingress.yaml
