apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    solvers:
    - dns01:
        route53:
          hostedZoneID: Z03786811Y5HZH3WOPZMF
    email: brad@bradandmarsha.com
    privateKeySecretRef:
      name: letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory
